// Generated by CoffeeScript 1.9.2

var express = require('express');

var path = require('path');

var mongoose = require('mongoose');

var  _ = require('underscore');

var Movie = require('./models/movie');

var bodyParser = require('body-parser');

var port = process.env.PORT || 3000;

var app = express();

  mongoose.connect('mongodb://localhost/nodetest');

  app.set('views', './views/pages');

  app.set('view engine', 'jade');

  app.use(bodyParser.json());

  app.use(express["static"](path.join(__dirname, 'bower_components')));

  app.listen(port);

  app.get('/', function(req, res) {
    Movie.fetch(function(err, movies) {
      if (err) {
        console.log(err);
      }
      res.render('index', {
        title: 'NodeTest 首页',
        movies: movies
      });
    });
  });

  app.get('/movie/:id', function(req, res) {
    var id;
    id = req.params.id;
     Movie.findById(id, function(err, movie) {
      if (err) {
        console.log(err);
      }
       res.render('detail', {
        title: "NodeTest " + movie.title + " 详情页",
        movie: movie
      });
    });
  });

  app.get('/admin/movie', function(req, res) {
     res.render('admin', {
      title: 'NodeTest 后台录入页',
      movie: {
        title: '',
        doctor: '',
        country: '',
        year: '',
        poster: '',
        flash: '',
        summary: '',
        language: ''
      }
    });
  });

  app.get('/admin/update/:id', function(req, res) {
    var id;
    id = req.params.id;
    if (id) {
       Movie.findById(id, function(err, movie) {
         res.render('admin', {
          title: 'NodeTest 后台更新页',
          movie: movie
        });
      });
    }
  });

  app.post('/admin/movie/new', function(res, req) {
    var _movie, id, movieObj;
    id = req.body.movie._id;
    movieObj = req.body.movie;
    if (id !== 'undefined') {
       Movie.findById(id, function(err, movie) {
        var _movie;
        if (err) {
          console.log(err);
        }
        _movie = _.extend(movie, movieObj);
         _movie.save(function(err, movie) {
          if (err) {
            console.log(err);
          }
           res.redirect("/movie/" + movie._id);
        });
      });
    } else {
      _movie = new Movie({
        doctor: movieObj.doctor,
        title: movieObj.title,
        country: movieObj.country,
        language: movieObj.language,
        year: movieObj.year,
        poster: movieObj.poster,
        summary: movieObj.summary,
        flash: movieObj.flash
      });
       _movie.save(function(err, movie) {
        if (err) {
          console.log(err);
        }
         res.redirect("/movie/" + movie._id);
      });
    }
  });

  app.get('/admin/list', function(req, res) {
     Movie.fetch(function(err, movies) {
      if (err) {
        console.log(err);
      }
       res.render('index', {
        title: 'NodeTest 列表页',
        movies: movies
      });
    });
  });


