// Generated by CoffeeScript 1.9.2
(function() {
  var Movie, _, app, bodyParser, express, mongoose, path, port;

  express = require('express');

  path = require('path');

  mongoose = require('mongoose');

  _ = require('underscore');

  Movie = require('./models/movie');

  bodyParser = require('body-parser');

  port = process.env.PORT || 3000;

  app = express();

  mongoose.connect('mongodb://localhost/nodetest');

  app.set('views', './views/pages');

  app.set('view engine', 'jade');

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.use(express["static"](path.join(__dirname, 'public')));

  app.locals.moment = require('moment');

  app.listen(port);

  app.get('/', function(req, res) {
    return Movie.fetch(function(err, movies) {
      if (err) {
        console.log(err);
      }
      return res.render('index', {
        title: 'NodeTest 首页',
        movies: movies
      });
    });
  });

  app.get('/movie/:id', function(req, res) {
    var id;
    id = req.params.id;
    return Movie.findById(id, function(err, movie) {
      if (err) {
        console.log(123);
        console.log(err);
      }
      return res.render('detail', {
        title: "NodeTest " + movie.title + " 详情页",
        movie: movie
      });
    });
  });

  app.get('/admin/movie', function(req, res) {
    return res.render('admin', {
      title: 'NodeTest 后台录入页',
      movie: {
        title: '',
        doctor: '',
        country: '',
        year: '',
        poster: '',
        flash: '',
        summary: '',
        language: ''
      }
    });
  });

  app.get('/admin/update/:id', function(req, res) {
    var id;
    id = req.params.id;
    if (id) {
      return Movie.findById(id, function(err, movie) {
        if (err) {
          console.log(123);
          console.log(err);
        }
        return res.render('admin', {
          title: 'NodeTest 后台更新页',
          movie: movie
        });
      });
    }
  });

  app.post('/admin/movie/new', function(req, res) {
    var _movie, id, movieObj;
    id = req.body.movie._id;
    movieObj = req.body.movie;
    if (id !== 'undefined') {
      return Movie.findById(id, function(err, movie) {
        var _movie;
        if (err) {
          console.log(err);
        }
        _movie = _.extend(movie, movieObj);
        return _movie.save(function(err, movie) {
          if (err) {
            console.log(err);
          }
          return res.redirect("/movie/" + movie._id);
        });
      });
    } else {
      _movie = new Movie({
        doctor: movieObj.doctor,
        title: movieObj.title,
        country: movieObj.country,
        language: movieObj.language,
        year: movieObj.year,
        poster: movieObj.poster,
        summary: movieObj.summary,
        flash: movieObj.flash
      });
      return _movie.save(function(err, movie) {
        if (err) {
          console.log(err);
        }
        return res.redirect("/movie/" + movie._id);
      });
    }
  });

  app.get('/admin/list', function(req, res) {
    return Movie.fetch(function(err, movies) {
      if (err) {
        console.log(err);
      }
      return res.render('list', {
        title: 'NodeTest 列表页',
        movies: movies
      });
    });
  });

  app["delete"]('/amin/list', function(req, res) {
    var id;
    id = req.query.id;
    if (id) {
      return Movie.remove({
        _id: id
      }, function(err, movie) {
        if (err) {
          return console.log(err);
        } else {
          return res.json({
            success: 1
          });
        }
      });
    }
  });

}).call(this);
